services:
  backend:
    build:
      context: ./backend
    container_name: durianpay-backend
    working_dir: /app
    environment:
      HTTP_ADDR: :8080
      OPENAPIYAML_LOCATION: ../openapi.yaml
      JWT_SECRET: dev-secret-replace-me
      JWT_EXPIRED: 24h
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/app

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ""
    container_name: durianpay-frontend
    depends_on:
      - backend
    ports:
      - "3001:80"

volumes:
  backend_data:
